// components/shared/ClickableWord.tsx
'use client';
import { useState } from 'react';
import type { PassageToken } from '@/lib/types';

interface Props {
  token: PassageToken;
  onOpen: (e: React.MouseEvent, token: PassageToken) => void;
  /** Extra inline styles applied to the ruby/span wrapper */
  style?: React.CSSProperties;
  /**
   * Visual claim state for this word:
   *  'vocab'    — added this session: solid jade underline + '+' badge
   *  null/undefined — unknown word: dotted faint underline, no badge
   */
  claimKind?: 'vocab' | null;
  /**
   * True when this is an SRS review word in the deck (and not freshly claimed): dotted
   * accent underline, matching how review words look in the passage body. Ignored when
   * claimKind is set.
   */
  isReviewWord?: boolean;
}

/**
 * A single clickable word that opens a definition popup.
 * Tokens without pinyin render as plain spans (punct / plain text).
 */
export default function ClickableWord({ token, onOpen, style, claimKind, isReviewWord }: Props) {
  const [hovered, setHovered] = useState(false);

  if (!token.pinyin || token.type === 'punct') return <span style={style}>{token.text}</span>;

  const borderStyle = claimKind === 'vocab'
    ? '1.5px solid var(--jade)'
    : isReviewWord
      ? '1.5px dotted var(--accent)'
      : '1px dotted color-mix(in srgb, var(--ink-faint) 55%, transparent)';

  const badgeColor = claimKind === 'vocab' ? 'var(--jade)' : 'transparent';

  return (
    <>
      <ruby
        onClick={e => onOpen(e, token)}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
        className="cursor-pointer"
        style={{
          borderBottom: borderStyle,
          background: hovered ? 'color-mix(in srgb, var(--accent) 12%, transparent)' : 'transparent',
          borderRadius: 3,
          paddingBottom: 1,
          transition: 'background .12s',
          ...style,
        }}
      >
        {token.text}
        <rt>{token.pinyin}</rt>
      </ruby>
      {/* Badge indicator */}
      <span
        aria-hidden="true"
        style={{
          display: 'inline',
          fontSize: '0.45em',
          verticalAlign: 'super',
          lineHeight: 0,
          fontFamily: 'var(--f-ui)',
          fontWeight: 700,
          pointerEvents: 'none',
          userSelect: 'none',
          color: badgeColor,
        }}
      >
        +
      </span>
    </>
  );
}

// svelte-poc/src/lib/components/ClickableWord.svelte
<script lang="ts">
  import type { PassageToken } from '$lib/types';

  // Port of components/shared/ClickableWord.tsx — a clickable ruby word that opens a
  // definition popup. Tokens without a reading render as plain text.
  interface Props {
    token: PassageToken;
    onOpen: (e: MouseEvent, token: PassageToken) => void;
    claimKind?: 'vocab' | null;
    isReviewWord?: boolean;
  }
  let { token, onOpen, claimKind = null, isReviewWord = false }: Props = $props();

  let hovered = $state(false);

  const borderStyle = $derived(
    claimKind === 'vocab'
      ? '1.5px solid var(--jade)'
      : isReviewWord
        ? '1.5px dotted var(--accent)'
        : '1px dotted color-mix(in srgb, var(--ink-faint) 55%, transparent)',
  );
  const badgeColor = $derived(claimKind === 'vocab' ? 'var(--jade)' : 'transparent');
</script>

{#if !token.reading || token.type === 'punct'}
  <span>{token.text}</span>
{:else}
  <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
  <ruby
    onclick={(e) => onOpen(e, token)}
    onkeydown={(e) => { if (e.key === 'Enter') onOpen(e as unknown as MouseEvent, token); }}
    onmouseenter={() => (hovered = true)}
    onmouseleave={() => (hovered = false)}
    style="cursor:pointer; border-bottom:{borderStyle}; background:{hovered
      ? 'color-mix(in srgb, var(--accent) 12%, transparent)'
      : 'transparent'}; border-radius:3px; padding-bottom:1px; transition:background .12s;"
  >{token.text}<rt>{token.reading}</rt></ruby><span
    aria-hidden="true"
    style="display:inline; font-size:0.45em; vertical-align:super; line-height:0; font-family:var(--f-ui); font-weight:700; pointer-events:none; user-select:none; color:{badgeColor};"
  >+</span>
{/if}
